version: "3.7"

services:
  # Apollo backend
  apollo-backend:
    container_name: apollo-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - apollo-network
    secrets:
      - database_user
      - database_password
      - default_username
      - default_password
      - jwt_secret
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      DATABASE_NAME: "apollo-database"
  # SQL database
  postgres:
    image: postgres:13.4@sha256:db7bd5d662c41b8d11dd479b58829b86d9fcf6e54d1ea831d9ee04f74db3faf2
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "apollo-data:/var/lib/postgresql/data"
    networks:
      - apollo-network
    secrets:
      - database_user
      - database_password
    environment:
      POSTGRES_USER_FILE: "/run/secrets/database_user"
      POSTGRES_PASSWORD_FILE: "/run/secrets/database_password"
      POSTGRES_DB: "apollo-database"

volumes:
  apollo-data:

networks:
  apollo-network:

secrets:
  database_user:
    file: ./secrets/database_user.secret
  database_password:
    file: ./secrets/database_password.secret
  default_username:
    file: ./secrets/default_username.secret
  default_password:
    file: ./secrets/default_password.secret
  jwt_secret:
    file: ./secrets/jwt_secret.secret
