name: CI

on:
  push:
    branches: [master, develop, feature/*, renovate/*]
  pull_request:
    branches: [master, develop, feature/*, renovate/*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
