name: CI

on:
  push:
    branches: [master, develop, feature/*, renovate/*, release/*]
  pull_request:
    branches: [master, develop, feature/*, renovate/*, release/*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 14
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
  documentation:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 14
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: dokkaHtml
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          branch: gh-pages
          folder: build/dokka/html
          clean: true
